import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Card from "./shared/components/card";

const Home: NextPage = () => {
  return (
    <div className={styles.flexContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.cardContainer}>
        <Card title={"Card 1"} url={"test"} image={"something"} />
      </div>
    </div>
  );
};

export default Home;
